<Project>
  <PropertyGroup>
    <RepoVersion>12.0.4</RepoVersion>
    <Version>$(RepoVersion)</Version>
    <FileVersion Condition="'$(FileVersion)' == ''">$(RepoVersion)</FileVersion>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(RepoVersion)</AssemblyVersion>
  </PropertyGroup>
</Project>
